#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    sys.stderr.write('Need a max bar size\n');
    sys.exit(-1)

bar_size = int(sys.argv[1])

# read input in
data = list(map(float, sys.stdin.readlines()))

# normalize, so the largest value goes to 1
largest_weight = max(data)
data = list(map(lambda x : x / largest_weight, data))

# now scale to figure out character count
data = list(map(lambda x : int(round(x * bar_size)), data))

# now print out the bars
for single_bar_size in data:
    print('#' * single_bar_size)
