#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    sys.stderr.write('Need a max bar size\n');
    sys.exit(-1)

bar_size = int(sys.argv[1])

# read input in
data = list(map(float, sys.stdin.readlines()))

# normalize to fit the bar size
total_weight = sum(data)
data = list(map(lambda x : int(round(x / total_weight * bar_size)), data))

# now print out the bars
for single_bar_size in data:
    print('#' * single_bar_size)
