#!/bin/bash

set -B

file=""

while :
do
    case "$1" in
        -f)
            file="$2"
            shift 2
            ;;
        *)
            break
    esac
done

total_lines=`cat $file | egrep "[0-9]+" | wc -l`
sum_string=`cat $file | egrep "[0-9]+" | tr "\n" "+" | sed "s/+$//g"`

echo "1.0 * ($sum_string) / $total_lines" | bc -l
