#!/bin/bash

# First unshift arguments to add exclusions
exclusions="()"
file=""

while :
do
    case "$1" in
        -e)
            exclusions="$exclusions|($2)"
            shift 2
            ;;
        -f)
            file="$2"
            shift 2
            ;;
        *)
            break
    esac
done

total_lines=`cat $file | wc -l`
sum_string=`cat $file | tr "\n" "+" | sed "s/+$//g"`

echo "1.0 * ($sum_string) / $total_lines" | bc -l
