#!/usr/bin/env python

import sys

def is_float(word):
    try:
        float(word)
    except ValueError:
        return False
    return True

# skipping non-numbers, convert stdin into numbers
numbers = list(map(float, filter(is_float, sys.stdin.readlines())))

# print the average
print(sum(numbers) * 1.0 / len(numbers))
