#!/usr/bin/env python

import sys

if len(sys.argv) == 1:
    sys.stderr.write('Need a boxcar width\n')
    sys.exit(-1)

box_car_width = int(sys.argv[1])

# first map to numbers
data = list(map(float, sys.stdin.readlines()))

if len(data) < (2 * box_car_width + 1):
    sys.stderr.write('Box car is too large for the data set. Data set is of size {0:d}\n'.format(len(data)))
    sys.exit(-1)

# the first chunk of points aren't smoothed
for index in range(box_car_width):
    print(data[index])

# the middles ARE smoothed
for index in range(box_car_width, len(data) - box_car_width):
    window = data[index - box_car_width : index + box_car_width + 1]
    window_average = sum(window) * 1.0 / len(window)
    print(window_average)

# the ends are not
for index in range(len(data) - box_car_width, len(data)):
    print(data[index])
