#!/bin/bash

if [ -z "$1" ]; then
    echo "Need a glob to pull from"
    exit 1
fi

# Gets the list of files to add:
# 1) find expands the glob
# 2) cut removes the file extension, leaving a timestamp
# 3) weekday_metro filters out weekend times
# 4) sed adds back the .json
# TODO: Don't use find, since bash will unpack files *.json becomes 1.json, 2.json, etc...
files_to_add=`find $@ | cut -d'.' -f1 | ./weekday_metro | sed 's/$/.json/g'`

total_files=`echo $files_to_add | wc -l`
file_index=1
for file in $files_to_add; do
    echo "Importing $file. $file_index of $total_files..."
    ./insert_train_status $file > /dev/null

    # increment
    file_index=$(($file_index + 1))
done
