#!/usr/bin/env python
from sys import stdin
from os.path import basename, splitext
from datetime import datetime

def timestampShouldBePrinted(timestamp):
    date = datetime.fromtimestamp(timestamp)

    # Ignore weekends
    if date.weekday() is 5 or date.weekday() is 6:
        return False

    # Ignore when closed
    if date.hour < 5:
        return False

    return True

for line in stdin.readlines():
    filename = line.strip()

    # convert the filename to a timestamp, by stripping the folder and extension
    timestamp = int(splitext(basename(filename))[0])

    if timestampShouldBePrinted(timestamp):
        print(filename)
